defmodule FreeqWeb3Web.Endpoint do
  use Phoenix.Endpoint, otp_app: :freeq_web3

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_freeq_web3_key",
    signing_salt: "clSTCWF2",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  # `only` matches the first path segment exactly (good for dirs).
  # Root digests are `favicon-<hash>.png` — use `only_matching` prefixes so
  # `mix phx.digest` filenames are served (exact `only: ["favicon.png"]` 404s).
  plug Plug.Static,
    at: "/",
    from: :freeq_web3,
    gzip: not code_reloading?,
    only: FreeqWeb3Web.static_paths(),
    only_matching: FreeqWeb3Web.static_path_prefixes(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug FreeqWeb3Web.Router
end
