import XCTest
import CryptoKit
@testable import FreeqMacosCore

/// Tests for the passphrase-based channel E2EE (ENC1 wire format).
///
/// The format must interoperate byte-for-byte with the Rust implementation
/// in `freeq-sdk/src/e2ee.rs` and the web client's `lib/e2ee.ts`:
///
///     ENC1:<nonce-base64>:<ciphertext+tag-base64>
///     key = HKDF-SHA256(ikm: passphrase, salt: SHA256(lowercased channel), info: "freeq-e2ee-v1")
///
/// The interop vectors below were generated by running the Rust
/// implementation (aes-gcm 0.10 / hkdf 0.12) with a fixed nonce.
final class ChannelCryptoTests: XCTestCase {

    // MARK: - Interop vectors (pinned against freeq-sdk/src/e2ee.rs)

    func testKeyDerivationMatchesRust() {
        let key = ChannelCrypto.deriveKey(passphrase: "hunter2", channel: "#Secret-Channel")
        XCTAssertEqual(
            key.withUnsafeBytes { Data($0).map { String(format: "%02x", $0) }.joined() },
            "f73b1643a38190d077993aa945e7aa9912685f2a1ca6f200b8f9a9292645172c"
        )
    }

    func testKeyDerivationUnicodeMatchesRust() {
        let key = ChannelCrypto.deriveKey(passphrase: "パスワード", channel: "#日本語")
        XCTAssertEqual(
            key.withUnsafeBytes { Data($0).map { String(format: "%02x", $0) }.joined() },
            "e6f0da4fa9408abc216cc97e86684a816cea0cf0c75649893b295d3acb5cbf06"
        )
    }

    func testDecryptsRustProducedWire() throws {
        let key = ChannelCrypto.deriveKey(passphrase: "hunter2", channel: "#Secret-Channel")
        let wire = "ENC1:AAECAwQFBgcICQoL:5GiMdLmq4bVHQeA7k9S+oTkPW+viI9X7Uqw42mj/Q92tCLSvmTel1rfeauQ="
        XCTAssertEqual(try ChannelCrypto.decrypt(key: key, wire: wire), "Hello, encrypted world! 🔐")
    }

    func testDecryptsRustProducedEmptyMessage() throws {
        let key = ChannelCrypto.deriveKey(passphrase: "hunter2", channel: "#Secret-Channel")
        let wire = "ENC1:AAECAwQFBgcICQoL:wVUxtYyAg79QKTqx6S1w6g=="
        XCTAssertEqual(try ChannelCrypto.decrypt(key: key, wire: wire), "")
    }

    func testEncryptWithFixedNonceMatchesRust() throws {
        let key = ChannelCrypto.deriveKey(passphrase: "hunter2", channel: "#Secret-Channel")
        let nonce = Data([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])
        let wire = try ChannelCrypto.encrypt(key: key, plaintext: "Hello, encrypted world! 🔐", nonce: nonce)
        XCTAssertEqual(wire, "ENC1:AAECAwQFBgcICQoL:5GiMdLmq4bVHQeA7k9S+oTkPW+viI9X7Uqw42mj/Q92tCLSvmTel1rfeauQ=")
    }

    // MARK: - Roundtrip behavior

    func testRoundtrip() throws {
        let key = ChannelCrypto.deriveKey(passphrase: "hunter2", channel: "#secret-channel")
        let wire = try ChannelCrypto.encrypt(key: key, plaintext: "Hello, encrypted world!")
        XCTAssertTrue(wire.hasPrefix("ENC1:"))
        XCTAssertTrue(ChannelCrypto.isEncrypted(wire))
        XCTAssertFalse(ChannelCrypto.isEncrypted("just a normal message"))
        XCTAssertEqual(try ChannelCrypto.decrypt(key: key, wire: wire), "Hello, encrypted world!")
    }

    func testRoundtripUnicode() throws {
        let key = ChannelCrypto.deriveKey(passphrase: "パスワード", channel: "#日本語")
        let plaintext = "こんにちは世界 🔐"
        let wire = try ChannelCrypto.encrypt(key: key, plaintext: plaintext)
        XCTAssertEqual(try ChannelCrypto.decrypt(key: key, wire: wire), plaintext)
    }

    func testRoundtripEmpty() throws {
        let key = ChannelCrypto.deriveKey(passphrase: "password", channel: "#test")
        let wire = try ChannelCrypto.encrypt(key: key, plaintext: "")
        XCTAssertEqual(try ChannelCrypto.decrypt(key: key, wire: wire), "")
    }

    func testRandomNoncesDiffer() throws {
        let key = ChannelCrypto.deriveKey(passphrase: "password", channel: "#test")
        let a = try ChannelCrypto.encrypt(key: key, plaintext: "same message")
        let b = try ChannelCrypto.encrypt(key: key, plaintext: "same message")
        XCTAssertNotEqual(a, b, "nonce must be random per message")
    }

    // MARK: - Key separation

    func testWrongKeyFails() throws {
        let key1 = ChannelCrypto.deriveKey(passphrase: "correct-password", channel: "#channel")
        let key2 = ChannelCrypto.deriveKey(passphrase: "wrong-password", channel: "#channel")
        let wire = try ChannelCrypto.encrypt(key: key1, plaintext: "secret stuff")
        XCTAssertThrowsError(try ChannelCrypto.decrypt(key: key2, wire: wire)) {
            XCTAssertEqual($0 as? ChannelCrypto.CryptoError, .decryptFailed)
        }
    }

    func testDifferentChannelsDifferentKeys() throws {
        let key1 = ChannelCrypto.deriveKey(passphrase: "same-password", channel: "#channel-a")
        let key2 = ChannelCrypto.deriveKey(passphrase: "same-password", channel: "#channel-b")
        let wire = try ChannelCrypto.encrypt(key: key1, plaintext: "test")
        XCTAssertThrowsError(try ChannelCrypto.decrypt(key: key2, wire: wire))
    }

    func testChannelSaltIsCaseInsensitive() {
        let key1 = ChannelCrypto.deriveKey(passphrase: "pw", channel: "#MixedCase")
        let key2 = ChannelCrypto.deriveKey(passphrase: "pw", channel: "#mixedcase")
        XCTAssertEqual(
            key1.withUnsafeBytes { Data($0) },
            key2.withUnsafeBytes { Data($0) }
        )
    }

    // MARK: - Malformed input

    func testNotEncryptedReturnsError() {
        let key = ChannelCrypto.deriveKey(passphrase: "password", channel: "#test")
        XCTAssertThrowsError(try ChannelCrypto.decrypt(key: key, wire: "just a plain message")) {
            XCTAssertEqual($0 as? ChannelCrypto.CryptoError, .notEncrypted)
        }
    }

    func testMissingColonIsMalformed() {
        let key = ChannelCrypto.deriveKey(passphrase: "password", channel: "#test")
        XCTAssertThrowsError(try ChannelCrypto.decrypt(key: key, wire: "ENC1:no-colon-here")) {
            XCTAssertEqual($0 as? ChannelCrypto.CryptoError, .malformed)
        }
    }

    func testBadBase64IsMalformed() {
        let key = ChannelCrypto.deriveKey(passphrase: "password", channel: "#test")
        XCTAssertThrowsError(try ChannelCrypto.decrypt(key: key, wire: "ENC1:!!!!:%%%%")) {
            XCTAssertEqual($0 as? ChannelCrypto.CryptoError, .malformed)
        }
    }

    func testWrongNonceLengthIsMalformed() {
        let key = ChannelCrypto.deriveKey(passphrase: "password", channel: "#test")
        // 8-byte nonce instead of 12
        let shortNonce = Data([1, 2, 3, 4, 5, 6, 7, 8]).base64EncodedString()
        XCTAssertThrowsError(try ChannelCrypto.decrypt(key: key, wire: "ENC1:\(shortNonce):AAAA")) {
            XCTAssertEqual($0 as? ChannelCrypto.CryptoError, .malformed)
        }
    }

    func testTamperedCiphertextFails() throws {
        let key = ChannelCrypto.deriveKey(passphrase: "password", channel: "#test")
        let wire = try ChannelCrypto.encrypt(key: key, plaintext: "hello")
        // Flip the last ciphertext character (stay within base64 alphabet).
        var tampered = wire
        let last = tampered.removeLast()
        tampered.append(last == "A" ? "B" : "A")
        XCTAssertThrowsError(try ChannelCrypto.decrypt(key: key, wire: tampered))
    }

    // MARK: - isEncrypted

    func testIsEncryptedPrefixOnly() {
        XCTAssertTrue(ChannelCrypto.isEncrypted("ENC1:x:y"))
        XCTAssertFalse(ChannelCrypto.isEncrypted("ENC2:x:y"))
        XCTAssertFalse(ChannelCrypto.isEncrypted(" ENC1:x:y"))
        XCTAssertFalse(ChannelCrypto.isEncrypted(""))
    }
}
