// Cross-implementation contract tests for act signing.
//
// The vectors in spec/act-signing-vectors.json are generated by the Rust
// implementation (`cargo test -p freeq-sdk generate_signing_vectors --
// --ignored`). This suite must reproduce every canonical, kid, and sigTag
// byte-for-byte — if any assertion here fails after a Rust-side change, the
// two implementations have diverged and signatures made by one will not
// verify on the other.

import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { importDidKey } from "@freeq/sdk";
import {
  actCanonical,
  deriveKid,
  publicKeyFromMultibase,
  signActTags,
  verifyActTags,
} from "./act.js";

interface Vector {
  name: string;
  seed: string;
  publicKey: string;
  kid: string;
  tags: Record<string, string>;
  canonical: string;
  sigTag: string;
}

const fixtures: { vectors: Vector[] } = JSON.parse(
  readFileSync(
    fileURLToPath(new URL("../../spec/act-signing-vectors.json", import.meta.url)),
    "utf8",
  ),
);

function hexToBytes(hex: string): Uint8Array {
  const out = new Uint8Array(hex.length / 2);
  for (let i = 0; i < out.length; i++) out[i] = parseInt(hex.slice(i * 2, i * 2 + 2), 16);
  return out;
}

function b64urlDecode(s: string): Uint8Array {
  return new Uint8Array(Buffer.from(s, "base64url"));
}

describe("act signing vectors (shared with Rust)", () => {
  for (const v of fixtures.vectors) {
    describe(v.name, () => {
      it("reproduces the canonical byte-for-byte", () => {
        expect(actCanonical(v.tags)).toBe(v.canonical);
      });

      it("derives the same kid", async () => {
        expect(await deriveKid(b64urlDecode(v.publicKey))).toBe(v.kid);
      });

      it("verifies the Rust-minted signature", async () => {
        expect(await verifyActTags(v.tags, v.sigTag, b64urlDecode(v.publicKey))).toEqual({
          ok: true,
        });
      });

      it("signs to the identical sigTag from the same seed (deterministic ed25519)", async () => {
        const key = await importDidKey(hexToBytes(v.seed));
        expect(publicKeyFromMultibase(key.publicKeyMultibase)).toEqual(
          b64urlDecode(v.publicKey),
        );
        expect(await signActTags(v.tags, key)).toBe(v.sigTag);
      });
    });
  }
});

describe("verification failures", () => {
  const v = fixtures.vectors[0];
  const pub = () => b64urlDecode(v.publicKey);

  it("altered covered tag → sig-invalid", async () => {
    const tampered = { ...v.tags, "+freeq.at/act-title": "Cite 4 sources on X" };
    expect(await verifyActTags(tampered, v.sigTag, pub())).toEqual({
      ok: false,
      reason: "sig-invalid",
    });
  });

  it("added act tag → sig-invalid; altered non-covered tag → still valid", async () => {
    const added = { ...v.tags, "+freeq.at/act-priority": "urgent" };
    expect(await verifyActTags(added, v.sigTag, pub())).toEqual({
      ok: false,
      reason: "sig-invalid",
    });
    const remintedMsgid = { ...v.tags, msgid: "01JREMINTEDBYPEER00000000" };
    expect(await verifyActTags(remintedMsgid, v.sigTag, pub())).toEqual({ ok: true });
  });

  it("wrong key → kid-mismatch", async () => {
    const otherPub = b64urlDecode(fixtures.vectors[1].publicKey);
    expect(await verifyActTags(v.tags, v.sigTag, otherPub)).toEqual({
      ok: false,
      reason: "kid-mismatch",
    });
  });

  it("malformed sig tag / unknown algorithm", async () => {
    expect(await verifyActTags(v.tags, "ed25519:only-one-colon", pub())).toEqual({
      ok: false,
      reason: "bad-sig-format",
    });
    expect(await verifyActTags(v.tags, "rsa:kid:c2ln", pub())).toEqual({
      ok: false,
      reason: "unsupported-algorithm",
    });
  });

  it("wrong-length signature → bad-sig-format (parity with Rust's BadSigFormat)", async () => {
    // Correct kid so the kid check passes; the payload decodes to 3 bytes, not
    // 64. base64url tolerates it silently, so without the length guard this
    // would fall through to a `sig-invalid` — diverging from Rust.
    const kid = v.sigTag.split(":")[1];
    expect(await verifyActTags(v.tags, `ed25519:${kid}:AAAA`, pub())).toEqual({
      ok: false,
      reason: "bad-sig-format",
    });
  });

  it("no act tags → no-act-tags (and signing returns null)", async () => {
    const none = { msgid: "01J", account: "did:plc:x" };
    expect(await verifyActTags(none, v.sigTag, pub())).toEqual({
      ok: false,
      reason: "no-act-tags",
    });
    const key = await importDidKey(hexToBytes(v.seed));
    expect(await signActTags(none, key)).toBeNull();
  });
});
